# Day 2 #

### 3.1) Continued Indexing ###
Slicing lists and arrays

In [145]:
months = ['jan','feb','march','april','may','june','july','aug','sep','oct','nov','dec']
print(months)

# Slices with :
print(months[6])
print(months[:])

# Summer months (indices 5, 6, and 7)
summer = months[5:8]
print(summer)

# The entire array, 5 left off the first and included in second
print(months[:5])
print(months[5:])
print(months[:5] + months[5:])
print(summer*3)

# Negative indexing
print(months[-1])
print(months[-3:-1])
print(months[9:-1])

['jan', 'feb', 'march', 'april', 'may', 'june', 'july', 'aug', 'sep', 'oct', 'nov', 'dec']
july
['jan', 'feb', 'march', 'april', 'may', 'june', 'july', 'aug', 'sep', 'oct', 'nov', 'dec']
['june', 'july', 'aug']
['jan', 'feb', 'march', 'april', 'may']
['june', 'july', 'aug', 'sep', 'oct', 'nov', 'dec']
['jan', 'feb', 'march', 'april', 'may', 'june', 'july', 'aug', 'sep', 'oct', 'nov', 'dec']
['june', 'july', 'aug', 'june', 'july', 'aug', 'june', 'july', 'aug']
dec
['oct', 'nov']
['oct', 'nov']


### 3.2) NumPy Arrays ###
Vectorized numerical operations<br/>
Matrix operations

In [138]:
import numpy as np

# Lists to numpy arrays
mylist = [3, 25, 6, 3, 73, 3]
myarray = np.array(mylist)
print(myarray)
print(myarray[3])
print(myarray*3)

# Vectors
v1 = np.array([1,-5,3])
v2 = np.array([2,1,0])
print(v1, v2)

# Elementwise multiplication
print(v1 * v2)

# Dot products
print(np.dot(v1, v2))
print(v1.dot(v2))
print(v1 @ v2)

# Cross product
print(np.cross(v1, v2))

[ 3 25  6  3 73  3]
3
[  9  75  18   9 219   9]
[ 1 -5  3] [2 1 0]
[ 2 -5  0]
-3
-3
-3
[-3  6 11]


In [150]:


# Create a matrix
matrixA = np.array([[1,2,3],[4,5,6]])
print(matrixA,'\n')

# Slices
print(matrixA[0,:], matrixA[1,:], '\n')
print(matrixA[:,0], matrixA[:,1], matrixA[:,2], '\n')

# Pre-allocating numpy containers
myarray2 = np.zeros((6,3))
print(myarray2)

# Reshape
matrixB = np.array(range(5,11)).reshape((2,3))
print(matrixB,'\n')

# Matrix tools
print(matrixA + matrixB, '\n') # Elementwise Addition
print(matrixA * matrixB, '\n') # Elementwise Multiplication
print(matrixA @ matrixB.T, '\n') # Matrix Multiplication
print(np.kron(matrixA, matrixB), '\n') # Tensor Product

# Matrix inverse
matrixC = np.array([[-1,1],[2,3]])
invC = np.linalg.inv(matrixC)
print(invC @ matrixC)

[[1 2 3]
 [4 5 6]] 

[1 2 3] [4 5 6] 

[1 4] [2 5] [3 6] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 5  6  7]
 [ 8  9 10]] 

[[ 6  8 10]
 [12 14 16]] 

[[ 5 12 21]
 [32 45 60]] 

[[ 38  56]
 [ 92 137]] 

[[ 5  6  7 10 12 14 15 18 21]
 [ 8  9 10 16 18 20 24 27 30]
 [20 24 28 25 30 35 30 36 42]
 [32 36 40 40 45 50 48 54 60]] 

[[ 1.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  1.00000000e+00]]


### 3.3) Control Flow ###
Logical branching

In [151]:
import numpy as np

np.random.seed(1234)
rnd_nums = np.random.randint(10, size=20)
print(rnd_nums)

if rnd_nums[0] == 5:
    print('Its five')
elif rnd_nums[0] == 4:
    print('Its four')
else:
    print('Its not five or four')

c1 = []
c2 = []
c3 = []
c4 = []
for num in rnd_nums:
    if num != 2:
        c1.append(num)
    if num > 4:
        c2.append(num)
    if num > 4 and num != 6:
        c3.append(num)
    if num == 2 or num == 6:
        c4.append(num)
print(c1)
print(c2)
print(c3)
print(c4)
        
large_inds = []
large_nums = []
for ind,num in enumerate(rnd_nums):
    if num >= 7:
        large_nums.append(num)
        large_inds.append(ind)
print(large_nums)
print(large_inds)



[3 6 5 4 8 9 1 7 9 6 8 0 5 0 9 6 2 0 5 2]
Its not five or four
[3, 6, 5, 4, 8, 9, 1, 7, 9, 6, 8, 0, 5, 0, 9, 6, 0, 5]
[6, 5, 8, 9, 7, 9, 6, 8, 5, 9, 6, 5]
[5, 8, 9, 7, 9, 8, 5, 9, 5]
[6, 6, 6, 2, 2]
[8, 9, 7, 9, 8, 9]
[4, 5, 7, 8, 10, 14]


### 3.5) Functions ###
Eliminate repition of code!

In [4]:
def threeXplus1 ( x ):
    return 3 * x + 1
print(threeXplus1(1))
print(threeXplus1(4))
n = 3
print(threeXplus1(n))

# Function to count occurances of a number
# Arguments:
#   nums (list): List of numbers
#   N (int): The number to count occurances of
# Returns:
#   (int) Occurance count
def count_Ns ( nums, N ):
    count = 0
    for n in nums:
        if n == N:
            count += 1
    return count

#N = 10
#np.random.seed(1234)
#rnd_nums = np.random.randint(N, size=20)

print(rnd_nums)
n3 = count_Ns(rnd_nums,3)
print(n3)
print('N | count')
for i in range(N):
    print(i, '|', count_Ns(rnd_nums, i))

4
13
10


NameError: name 'rnd_nums' is not defined

### 3.6) Dictionaries ###
Simple storage and fast lookups<br/>
{key : value} pairs

In [149]:
mydict = { 'key1':10 }
print(mydict)
print(mydict['key1'])

mydict['key2'] = -1
print(mydict)

if 'key1' in mydict:
    print('Its here')

del mydict['key1']
print(mydict)

if 'key1' in mydict:
    print('Its here')

def check_for_key ( dct, key ):
    if key in dct:
        print(key, 'is here')
    else:
        print(key, 'is not here')

check_for_key(mydict, 'key1')
check_for_key(mydict, 'key2')

{'key1': 10}
10
{'key1': 10, 'key2': -1}
Its here
{'key2': -1}
key1 is not here
key2 is here


In [100]:
def count_all ( nums ):
    count = {}
    for n in nums:
        if n not in count:
            count[n] = 0
        count[n] += 1
    return count

cnt_dict = count_all(rnd_nums)
print(cnt_dict)
for i in range(N):
    print(i, '|', cnt_dict[i])

{3: 1, 6: 3, 5: 3, 4: 1, 8: 2, 9: 3, 1: 1, 7: 1, 0: 3, 2: 2}
0 | 3
1 | 1
2 | 2
3 | 1
4 | 1
5 | 3
6 | 3
7 | 1
8 | 2
9 | 3


### 3.4) Nested Loops (Bubble Sort) ###
Sorting a list the trivial way<br/>
[<span style="color:blue">9</span>,5,7,4,1] -> [5,<span style="color:red">7</span>,4,1,<span style="color:blue">9</span>] -> [<span style="color:green">5</span>,4,1,<span style="color:red">7</span>,9] -> [<span style="color:blue">4</span>,1,<span style="color:green">5</span>,7,9] -> [1,<span style="color:blue">4</span>,5,7,9]

In [102]:

for i in range(rnd_nums.shape[0]-1):
    for j in range(i+1, rnd_nums.shape[0]):
        if rnd_nums[i] > rnd_nums[j]:
            rnd_nums[i],rnd_nums[j] = rnd_nums[j],rnd_nums[i]
print(rnd_nums)

[0 0 0 1 2 2 3 4 5 5 5 6 6 6 7 8 8 9 9 9]
